on:
  push:
    branches:
      - main
    paths:
      - "iq_tree_capitator/**"
      - "pyproject.toml"
      - ".github/workflows/static.yaml"
  pull_request:
    paths:
      - "iq_tree_capitator/**"
      - "pyproject.toml"
      - ".github/workflows/static.yaml"

name: Static Analysis
jobs:
  mypy-check:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy

      - name: Run mypy analysis
        run: |
          mypy

  ruff-check:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check code
        run: ruff check

      - name: Check format
        run: ruff format --check
